### ISSUE TITLE
input.aoc is all puzzles in 1 file?

### ISSUE THREAD

**Issue by xcom169** [itsBuggingMe/AdventOfCode2024#1]
Combine all days to 1 file?

**Comment by itsBuggingMe** [comment]
The `AdventOfCode2024` repository expects `input.aoc` as a single day's input, and it runs the most recent day
The `AdventOfOneLine` expects 25 `.aoc` files in the working directory. So the working directory will have `day1.aoc`, `day2.aoc`, all the way to `day25.aoc`.

**Comment by xcom169** [comment]
Thanks!  I'll try.
